// Phase 3 step 13: `npm run embed` — batch-embeds the QA corpus (chatContent.js's
// CHAT_CHIPS + qaBank.js's QA_BANK) into src/content/embeddings.json.
//
// Run this whenever chip or QA bank content changes; embeddings.json is a
// committed, versioned static file (ERD: "/content/embeddings.json,
// generated by a build-time script"), not regenerated on every build.
//
// Needs a real GEMINI_API_KEY in the environment. Vercel's Sensitive env
// vars (which is what this project's GEMINI_API_KEY is set as, deliberately
// — see .env.example) are never retrievable via `vercel env pull`, so this
// has to be run with the key available some other way: a local `.env.local`
// you've set yourself (see README), or in a CI/build context where Vercel
// has injected it directly into process.env.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { buildCorpus, embedCorpus } from './embed-core.mjs';
import { CHAT_CHIPS } from '../src/content/chatContent.js';
import { QA_BANK } from '../src/content/qaBank.js';

const apiKey = process.env.GEMINI_API_KEY;
if (!apiKey || /^placeholder/i.test(apiKey)) {
  console.error(
    'GEMINI_API_KEY is not set (or is still the placeholder). Set a real key in your environment before running `npm run embed` — see README.md.',
  );
  process.exit(1);
}

const rootDir = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.join(rootDir, '..', 'src', 'content', 'embeddings.json');

const corpus = buildCorpus(CHAT_CHIPS, QA_BANK);
console.log(`Embedding ${corpus.length} QA pairs (${CHAT_CHIPS.length} chips + ${QA_BANK.length} QA bank entries)...`);

const rows = await embedCorpus(corpus, apiKey);
writeFileSync(outPath, JSON.stringify(rows, null, 2) + '\n');
console.log(`Wrote ${rows.length} embedding rows to src/content/embeddings.json`);
